services:
  # Serviço do backend (FastAPI)
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: cinema-explorer-backend
      env_file:
        - .env
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/app  
      networks:
        - cinema-network
      command: fastapi dev app/main.py --host 0.0.0.0 --port 8000 --reload

  # Serviço do frontend (Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cinema-explorer-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - cinema-network
    command: npm run dev -- --host 0.0.0.0

networks:
  cinema-network:
    driver: bridge